version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anpr-platform-app
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - mlflow
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload

  postgres:
    image: postgis/postgis:16-3.4
    container_name: anpr-postgres
    environment:
      POSTGRES_DB: anpr_traffic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.19.0
    container_name: anpr-mlflow
    ports:
      - "5000:5000"
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri sqlite:///mlflow.db --default-artifact-root /mlflow/artifacts
    volumes:
      - mlflow_data:/mlflow

volumes:
  postgres_data:
  mlflow_data:
